version: '2'
services:
    volo-app:
        image: volo
        external_links:
            - volo-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=volo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    volo-mongodb:
        extends:
            file: mongodb.yml
            service: volo-mongodb
