version: '2'
services:
    volo-mongodb:
        container_name: volo-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/volo/mongodb/:/data/db/
